require('dotenv').config();
const mongoose = require('mongoose');
const Crop = require('./models/Crop');
const connectDB = require('./config/database');

const seedCrops = async () => {
    try {
        await connectDB();

        // Clear existing crops
        await Crop.deleteMany({});

        const crops = [
            {
                cropName: 'Rice',
                cropImage: 'https://via.placeholder.com/300x200?text=Rice',
                description: 'Staple crop, high demand in market',
                soilTypeRequired: ['Clay', 'Loamy', 'Silty'],
                idealPHRange: { min: 5.5, max: 7.5 },
                waterRequirement: 'High',
                waterNeededPerDay: 8,
                growingSeason: 'Monsoon',
                daysToMaturity: 120,
                temperatureRange: { min: 20, max: 35 },
                estimatedYield: { value: 5000, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 1500,
                    fertiliserCost: 5000,
                    waterCost: 3000,
                    labourCost: 8000,
                    totalCost: 17500
                },
                marketPrice: 2500,
                profitMargin: 25,
                nutrients: { nitrogen: 'High', phosphorus: 'Medium', potassium: 'High' },
                pests: ['Rice Stem Borer', 'Leaf Folder', 'Gall Midge'],
                diseases: ['Leaf Blast', 'Sheath Rot', 'False Smut'],
                pestControlMethods: ['IPM', 'Neem Spray', 'Biological Control'],
                diseaseControl: ['Resistant Varieties', 'Proper Spacing', 'Fungicide'],
                marketingChannels: ['APMC', 'Cooperative', 'Direct Sale'],
                storageLife: '1-2 years',
                alternateUses: ['Animal Feed', 'Straw'],
                companionPlants: ['Fish', 'Vegetables'],
                intercropSuggestions: ['Vegetables', 'Pulses']
            },
            {
                cropName: 'Wheat',
                cropImage: 'https://via.placeholder.com/300x200?text=Wheat',
                description: 'Winter crop with good market value',
                soilTypeRequired: ['Loamy', 'Sandy Loam', 'Silty'],
                idealPHRange: { min: 6.0, max: 7.5 },
                waterRequirement: 'Medium',
                waterNeededPerDay: 4,
                growingSeason: 'Winter',
                daysToMaturity: 120,
                temperatureRange: { min: 5, max: 25 },
                estimatedYield: { value: 4500, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 2000,
                    fertiliserCost: 4500,
                    waterCost: 2000,
                    labourCost: 6000,
                    totalCost: 14500
                },
                marketPrice: 2000,
                profitMargin: 35,
                nutrients: { nitrogen: 'High', phosphorus: 'Medium', potassium: 'Medium' },
                pests: ['Armyworm', 'Termites', 'Cutworm'],
                diseases: ['Rust', 'Powdery Mildew', 'Foot Rot'],
                pestControlMethods: ['IPM', 'Insecticides', 'Cultural Practices'],
                diseaseControl: ['Resistant Varieties', 'Fungicide Spray'],
                marketingChannels: ['APMC', 'Government Procurements', 'Direct Sale'],
                storageLife: '2-3 years',
                alternateUses: ['Animal Feed', 'Straw for Bedding'],
                companionPlants: ['Legumes'],
                intercropSuggestions: ['Pulses', 'Oilseeds']
            },
            {
                cropName: 'Cotton',
                cropImage: 'https://via.placeholder.com/300x200?text=Cotton',
                description: 'Cash crop with high market value',
                soilTypeRequired: ['Loamy', 'Clay', 'Sandy Loam'],
                idealPHRange: { min: 6.0, max: 8.0 },
                waterRequirement: 'High',
                waterNeededPerDay: 6,
                growingSeason: 'Summer',
                daysToMaturity: 160,
                temperatureRange: { min: 20, max: 35 },
                estimatedYield: { value: 2500, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 3000,
                    fertiliserCost: 6000,
                    waterCost: 4000,
                    labourCost: 10000,
                    totalCost: 23000
                },
                marketPrice: 5500,
                profitMargin: 45,
                nutrients: { nitrogen: 'High', phosphorus: 'High', potassium: 'High' },
                pests: ['Boll Worm', 'Cotton Bug', 'Mites'],
                diseases: ['Leaf Curl', 'Wilt', 'Root Rot'],
                pestControlMethods: ['Integrated Pest Management', 'Bt Cotton', 'Pesticide Spray'],
                diseaseControl: ['Resistant Varieties', 'Proper Rotation'],
                marketingChannels: ['APMC', 'Mill Direct', 'Traders'],
                storageLife: '2 years',
                alternateUses: ['Seed Oil', 'Cotton Cake'],
                companionPlants: ['Legumes'],
                intercropSuggestions: ['Pulses']
            },
            {
                cropName: 'Sugarcane',
                cropImage: 'https://via.placeholder.com/300x200?text=Sugarcane',
                description: 'Long duration crop with high returns',
                soilTypeRequired: ['Loamy', 'Clay', 'Alluvial'],
                idealPHRange: { min: 6.0, max: 8.0 },
                waterRequirement: 'High',
                waterNeededPerDay: 7,
                growingSeason: 'Annual',
                daysToMaturity: 360,
                temperatureRange: { min: 15, max: 32 },
                estimatedYield: { value: 70, unit: 'tons/hectare' },
                estimatedCost: {
                    seedCost: 3000,
                    fertiliserCost: 8000,
                    waterCost: 5000,
                    labourCost: 12000,
                    totalCost: 28000
                },
                marketPrice: 3000,
                profitMargin: 40,
                nutrients: { nitrogen: 'High', phosphorus: 'High', potassium: 'High' },
                pests: ['Shoot Borer', 'Scale Insects'],
                diseases: ['Ratoon Stunting', 'Red Rot'],
                pestControlMethods: ['Resistant Varieties', 'Biological Control'],
                diseaseControl: ['Clean Seed', 'Proper Field Hygiene'],
                marketingChannels: ['Sugar Mills', 'Direct Sale'],
                storageLife: '1 month (fresh)',
                alternateUses: ['Juice', 'Molasses', 'Bagasse'],
                companionPlants: ['Legumes', 'Root crops'],
                intercropSuggestions: ['Vegetables', 'Pulses']
            },
            {
                cropName: 'Potato',
                cropImage: 'https://via.placeholder.com/300x200?text=Potato',
                description: 'High value vegetable crop',
                soilTypeRequired: ['Sandy Loam', 'Loamy'],
                idealPHRange: { min: 5.5, max: 7.5 },
                waterRequirement: 'Medium',
                waterNeededPerDay: 5,
                growingSeason: 'Winter',
                daysToMaturity: 90,
                temperatureRange: { min: 10, max: 20 },
                estimatedYield: { value: 25000, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 12000,
                    fertiliserCost: 3000,
                    waterCost: 2000,
                    labourCost: 5000,
                    totalCost: 22000
                },
                marketPrice: 1000,
                profitMargin: 50,
                nutrients: { nitrogen: 'High', phosphorus: 'Medium', potassium: 'High' },
                pests: ['Colorado Beetle', 'Aphids', 'Whiteflies'],
                diseases: ['Blight', 'Wilt', 'Scab'],
                pestControlMethods: ['IPM', 'Neem Oil', 'Insecticides'],
                diseaseControl: ['Fungicide Spray', 'Proper Spacing'],
                marketingChannels: ['Market', 'Wholesale', 'Direct Sale'],
                storageLife: '3-6 months',
                alternateUses: ['Starch', 'Animal Feed'],
                companionPlants: ['Corn', 'Beans'],
                intercropSuggestions: ['Vegetables']
            },
            {
                cropName: 'Maize',
                cropImage: 'https://via.placeholder.com/300x200?text=Maize',
                description: 'Versatile crop for multiple uses',
                soilTypeRequired: ['Sandy Loam', 'Loamy', 'Clay Loam'],
                idealPHRange: { min: 6.0, max: 7.5 },
                waterRequirement: 'Medium',
                waterNeededPerDay: 5,
                growingSeason: 'Summer',
                daysToMaturity: 120,
                temperatureRange: { min: 8, max: 30 },
                estimatedYield: { value: 6000, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 2500,
                    fertiliserCost: 4000,
                    waterCost: 2000,
                    labourCost: 5000,
                    totalCost: 13500
                },
                marketPrice: 1800,
                profitMargin: 40,
                nutrients: { nitrogen: 'High', phosphorus: 'Medium', potassium: 'Medium' },
                pests: ['Stem Borer', 'Shoot Fly'],
                diseases: ['Leaf Spot', 'Rust', 'Downy Mildew'],
                pestControlMethods: ['Hybrid Seeds', 'Insecticide Spray'],
                diseaseControl: ['Fungicide', 'Resistant Varieties'],
                marketingChannels: ['APMC', 'Traders', 'Mill'],
                storageLife: '2-3 years',
                alternateUses: ['Animal Feed', 'Oil', 'Starch'],
                companionPlants: ['Beans', 'Pumpkin'],
                intercropSuggestions: ['Pulses', 'Vegetables']
            },
            {
                cropName: 'Tomato',
                cropImage: 'https://via.placeholder.com/300x200?text=Tomato',
                description: 'High value vegetable with good market demand',
                soilTypeRequired: ['Loamy', 'Sandy Loam'],
                idealPHRange: { min: 6.0, max: 7.5 },
                waterRequirement: 'Medium',
                waterNeededPerDay: 4,
                growingSeason: 'Summer',
                daysToMaturity: 60,
                temperatureRange: { min: 15, max: 28 },
                estimatedYield: { value: 40000, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 2000,
                    fertiliserCost: 3500,
                    waterCost: 2000,
                    labourCost: 8000,
                    totalCost: 15500
                },
                marketPrice: 800,
                profitMargin: 55,
                nutrients: { nitrogen: 'High', phosphorus: 'Medium', potassium: 'High' },
                pests: ['Fruit Borer', 'Whitefly', 'Mites'],
                diseases: ['Early Blight', 'Late Blight', 'Wilt'],
                pestControlMethods: ['IPM', 'Neem Spray', 'Insecticide'],
                diseaseControl: ['Fungicide Spray', 'Resistant Variety'],
                marketingChannels: ['Market', 'Wholesale', 'Processing Units'],
                storageLife: '5-7 days (fresh)',
                alternateUses: ['Paste', 'Juice', 'Sauce'],
                companionPlants: ['Basil', 'Onion'],
                intercropSuggestions: ['Vegetables', 'Herbs']
            },
            {
                cropName: 'Onion',
                cropImage: 'https://via.placeholder.com/300x200?text=Onion',
                description: 'Essential vegetable crop with stable demand',
                soilTypeRequired: ['Loamy', 'Sandy Loam', 'Clay Loam'],
                idealPHRange: { min: 6.0, max: 8.0 },
                waterRequirement: 'Medium',
                waterNeededPerDay: 4,
                growingSeason: 'Winter',
                daysToMaturity: 150,
                temperatureRange: { min: 10, max: 25 },
                estimatedYield: { value: 30000, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 2500,
                    fertiliserCost: 3000,
                    waterCost: 1500,
                    labourCost: 6000,
                    totalCost: 13000
                },
                marketPrice: 500,
                profitMargin: 60,
                nutrients: { nitrogen: 'Medium', phosphorus: 'Low', potassium: 'Medium' },
                pests: ['Thrips', 'Maggots'],
                diseases: ['Purple Blotch', 'Fusarium Rot'],
                pestControlMethods: ['Neem Oil', 'Insecticide'],
                diseaseControl: ['Fungicide', 'Good Drainage'],
                marketingChannels: ['Market', 'Wholesale', 'Storage Units'],
                storageLife: '4-6 months',
                alternateUses: ['Pickle', 'Powder'],
                companionPlants: ['Carrot', 'Lettuce'],
                intercropSuggestions: ['Vegetables']
            },
            {
                cropName: 'Chickpea',
                cropImage: 'https://via.placeholder.com/300x200?text=Chickpea',
                description: 'Protein-rich pulse crop',
                soilTypeRequired: ['Clay', 'Loamy', 'Sandy Loam'],
                idealPHRange: { min: 6.0, max: 8.0 },
                waterRequirement: 'Low',
                waterNeededPerDay: 2,
                growingSeason: 'Winter',
                daysToMaturity: 100,
                temperatureRange: { min: 5, max: 25 },
                estimatedYield: { value: 2000, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 1500,
                    fertiliserCost: 2000,
                    waterCost: 500,
                    labourCost: 3000,
                    totalCost: 7000
                },
                marketPrice: 4500,
                profitMargin: 65,
                nutrients: { nitrogen: 'Low', phosphorus: 'Medium', potassium: 'Low' },
                pests: ['Pod Borer', 'Beetle'],
                diseases: ['Wilt', 'Blight'],
                pestControlMethods: ['IPM', 'Neem Spray'],
                diseaseControl: ['Resistant Varieties'],
                marketingChannels: ['APMC', 'Cooperative', 'Dal Mills'],
                storageLife: '1-2 years',
                alternateUses: ['Dal', 'Pasta', 'Flour'],
                companionPlants: ['Cereal Crops'],
                intercropSuggestions: ['Cereals']
            },
            {
                cropName: 'Chili',
                cropImage: 'https://via.placeholder.com/300x200?text=Chili',
                description: 'Spice crop with high market value',
                soilTypeRequired: ['Loamy', 'Sandy Loam'],
                idealPHRange: { min: 6.0, max: 8.0 },
                waterRequirement: 'Medium',
                waterNeededPerDay: 4,
                growingSeason: 'Summer',
                daysToMaturity: 150,
                temperatureRange: { min: 15, max: 30 },
                estimatedYield: { value: 2500, unit: 'kg/hectare' },
                estimatedCost: {
                    seedCost: 3000,
                    fertiliserCost: 4000,
                    waterCost: 2500,
                    labourCost: 8000,
                    totalCost: 17500
                },
                marketPrice: 8000,
                profitMargin: 70,
                nutrients: { nitrogen: 'High', phosphorus: 'Medium', potassium: 'High' },
                pests: ['Mites', 'Thrips', 'Fruit Borer'],
                diseases: ['Leaf Spot', 'Anthracnose'],
                pestControlMethods: ['Neem Oil', 'Sulfur Dust'],
                diseaseControl: ['Fungicide', 'Crop Rotation'],
                marketingChannels: ['Spice Market', 'Processing Units', 'Export'],
                storageLife: '6 months',
                alternateUses: ['Pepper Powder', 'Sauce'],
                companionPlants: ['Basil'],
                intercropSuggestions: ['Vegetables']
            }
        ];

        await Crop.insertMany(crops);
        console.log(`✅ ${crops.length} crops seeded successfully!`);
        process.exit(0);

    } catch (error) {
        console.error('❌ Seeding Error:', error);
        process.exit(1);
    }
};

seedCrops();
